spring.application.name=TodoRails Elite Starter Code
logging.level.org.springframework.web=DEBUG
spring.devtools.restart.enabled=true

# MySQL database configurations
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/todorails?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:springstudent}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:springstudent}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA and Hibernate configurations
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false

# Ensure Thymeleaf Is Properly Configured
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.web.resources.static-locations=classpath:/static/,classpath:/public/




